import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "./(routes)/(root)/components";
import { Footer, Navbar } from "@/components/Shared";

// import { Variable } from "lucide-react";


const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${montserrat.variable}  antialiased`}>
          <SidebarProvider>
            <AppSidebar />
            <div className="w-full bg-[#0D0C11] flex flex-col min-h-screen">

              <Navbar />
              <main className="flex-1">
                {children}
              </main>

              <Footer />

            </div>
          </SidebarProvider>

        </body>
      </html>
    </ClerkProvider>

  );
}
